strawberry_mojito = Drink.create(name: "Strawberry Mojito", recipe: "11 oz strawberries, 1/3 cup fresh lime juice, 1/4 cup granulated sugar, 10 large fresh mint leaves, 1 cup white, 1 cup seltzer, Mint sprigs, to garnish", image: "https://source.unsplash.com/JdaZIXXqVtc")
blue_hawaiian = Drink.create(name: "Blue Hawaiian", recipe: "3/4 oz
Vodka, 3/4 oz Light rum, 1/2 oz Blue curaçao, 3 oz Pineapple juice, 1 oz Sweet-and-sour mix", image: "https://source.unsplash.com/9mlR8ATgsCE")
asia_daisy = Drink.create(name: "Asia Daisy", recipe: "1 lime, quartered Ice cubes, plus crushed ice, 2 ounces gin, 3/4 ounce lychee liqueur, 3/4 ounce Simple Syrup, 3/4 ounce chilled ginger ale, 1 fresh or canned lychee", image: "https://source.unsplash.com/G7jw4HTCod0")
champagne_cocktail = Drink.create(name: "Champagne Cocktail", recipe: "1 sugar cube, 2-3 dashes Angostura bitters,
brut champagne", image:"https://source.unsplash.com/SumkAubh9dA")
red_sangria =  Drink.create(name: "Grand Sangria", recipe: "1⁄2 cup Grand Marnier, 1 cup seedless red or black grapes, 2 lemons sliced, 1 orange sliced, 2 apples, red and green, cored and cut into 1/2 inch wedges, 2 cinnamon sticks, 1 tbsp superfine sugar, 1 cup orange juice, 1 bottle Casa Lapostolle Merlot, chilled", image: "https://source.unsplash.com/NXKpCCO9AMo")
mojito = Drink.create(name: "Mojito", recipe: "2 oz white rum, 3 mint Leaves, 3/4 oz fresh lime juice, 1/2 oz simple syrup, club soda, to top", image: "https://source.unsplash.com/pb7oJwtNVU4")
old_fashioned =  Drink.create(name: "Old Fashioned", recipe: "2 oz bourbon, 1/2 tsp white sugar, 3 dashes Angostura bitters, 1 dash Regan's Orange Bitters No. 6, 1/4 oz cold water, 1 brown sugar cube", image: "https://source.unsplash.com/gj7BLlSzIFs")
gin_tonic = Drink.create(name: "Gin and Tonic", recipe:"1 1/2 oz gin,
tonic water", image: "https://source.unsplash.com/GKo0ca66O5U")
berry_mojito =  Drink.create(name: "Berry Moito", recipe: "2 tbsp fresh blackberries, 2 tbsp fresh raspberries, 6 mint leaves, 2 tsp Truvia sweetener, 2 large lime wedges, 4 oz rum, Seltzer water", image: "https://source.unsplash.com/etblEGi3krw")
strawberry_margarita = Drink.create(name: "Strawberry Margarita", recipe: "3 Medium strawberries, 3 Basil leaves, 3/4 oz Lime juice, 3/4 oz Simple syrup, 1 1/2 oz Tequila, 1/2 oz Cointreau, 1/4 oz Maraschino liqueur", image: "https://source.unsplash.com/2EBTwzczg2A")
chocolate_cocktail = Drink.create(name: "White Russian", recipe: "2 oz vodka, 1 oz Kahlúa, Heavy cream", image: "https://source.unsplash.com/A_SOanq9Qdo")
red_pepper_martini = Drink.create(name: "Sweet Pepper Martini", recipe:" 1/4 cup roasted bell pepper strips, 4 Tbsp fresh squeezed orange juice, 1/4 cup simple syrup or agave syrup, 2 strawberries, thinly sliced, 2 basil leaves, cut into strips, 1 dash hot sauce, 1/4 tsp ground black pepper 1/2 cup vodka or gin, 4 sweet cherry peppers, to garnish", image: "https://source.unsplash.com/nY5DJyAcxE4")
rum_and_citrus = Drink.create(name: "Rum and Citrus Splash", recipe:"1/2 cup silver rum, 1/2 cup spiced rum, 3/4 cup fresh squeezed orange juice, 3/4 cup fresh squeezed grapefruit juice, 3/4 cup emonade, 3/4 cup limeade, 2 Tablespoons fresh squeezed lime juice, 1/2 cup ginger simple syrup, or more to taste", image:"https://source.unsplash.com/22fsBrruHPQ")
malibu_sunrise = Drink.create(name: "Malibu Sunrise", recipe:"2 oz. mixed pineapple and cranberry juice, 2 oz. 7-Up, 1/2 oz. lime juice, 1-1/4 oz. shot Malibu Coconut Rum" , image:"https://source.unsplash.com/Cllo-MF8CrI")
blue_lagoon = Drink.create(name:"Blue Lagoon", recipe:"1 oz Vodka, 1 oz Blue curaçao, 4 oz Lemonade" , image: "https://source.unsplash.com/ZFM4gN--PZI")

Review.create(drink_id: 1, name:"Lisa", comment:"Great twist on a classic")
Review.create(drink_id: 1, name:"Tracy", comment:"Refresing")
Review.create(drink_id: 1, name:"Lisa", comment:"Very delicious")
# Review.create(drink_id: 4, name:"Mary", comment:"Refreshing")
# Review.create(drink_id: 5, name:"Jane", comment:"Very delicious")
# Review.create(drink_id: 6, name:"Mike", comment:"Good")
# Review.create(drink_id: 7, name:"Beth", comment:"Very delicious")
# Review.create(drink_id: 8, name:"Tina", comment:"Very delicious")
# Review.create(drink_id: 9, name:"Alicia", comment:"Very delicious")
# Review.create(drink_id: 10, name:"Aretha", comment:"Classic!")
# Review.create(drink_id: 11, name:"Ike", comment:"Delicious")
# Review.create(drink_id: 12, name:"John", comment:"Fancy")
# Review.create(drink_id: 13, name:"SZA", comment:"Very delicious")
# Review.create(drink_id: 14, name:"Kelly", comment:"Very delicious")
# Review.create(drink_id: 15, name:"Mark", comment:"Very delicious")
